# Generated by Django 3.0 on 2019-12-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetBoxConfluenceField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='Model Name', max_length=255, verbose_name='Model Name')),
                ('field_type', models.CharField(choices=[('TextLinkedField', 'Text Linked Field'), ('StatusLinkedField', 'Drop down field.')], help_text='Field Type', max_length=255, verbose_name='Type')),
                ('is_custom_field', models.BooleanField(default=False, help_text='Is the field `custom field`?', verbose_name='Is Custom Field')),
                ('field_name', models.CharField(max_length=255, verbose_name='Field')),
            ],
            options={
                'unique_together': {('model_name', 'field_name', 'is_custom_field')},
            },
        ),
    ]
